# Generated by Django 4.1.3 on 2022-11-19 23:47

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_imagepost_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=todo.models.upload_to),
        ),
    ]
