# Generated by Django 4.1.3 on 2022-11-23 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_imagepost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(related_name='image_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
