# Generated by Django 4.1.3 on 2022-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_imagepost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
