# Generated by Django 4.1.3 on 2022-11-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_imagepost_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
