# Generated by Django 4.1.3 on 2022-12-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_imagepost_likes_alter_imagepost_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'ordering': ['created_on']},
        ),
    ]
