# Generated by Django 4.1.3 on 2022-12-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
